services:
  - type: web
    name: reedoy-payroll
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: reedoy-payroll-db
          property: connectionString
databases:
  - name: reedoy-payroll-db
